spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=usbc_db
    username: sa
    password: your_password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  application:
    name: Counterparty-api

server:
  port: 8080

schema:
  counterparty-schema-path: schemas/counterparty-request-schema.json
